apiVersion: v1
kind: Config
clusters:
- name: "open"
  cluster:
    server: "https://cluster01.evoliatis.fr:60443/k8s/clusters/c-2k6fs"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJxRENDQ\
      VUyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
      GNOTWpJdwpOakV3TURrek1ETXhXaGNOTXpJd05qQTNNRGt6TURNeFdqQTdNUnd3R2dZRFZRUUtFe\
      E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
      1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNmTzZ4KzFSZlQrb\
      mYxNWV1YjZxS0J0YzdpbFl5MGRTeTB1QWl5T3I2ZwoxYXlGM1dFa25lNCtDNmxDakhoUUhiSjFFV\
      2dwYzB1ZTlWQ3RBNUZqbVAzM28wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
      UgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVYWRKUmRCZjBPL1gzclFpdGZsRjcKTk1IMUJDZ3dDZ\
      1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBTGxVRmlST05uNzdvaG5EMzFMR0k1YkhvNXZCYXJVVAoxU\
      zNWYkZzeWc2WDhBaUVBL2d6VEFDNW0vbGtBNnVReVFyZUE2REF0ZXlEWW90M0FuZ1NnWGFVb2xrc\
      z0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
- name: "open-cluster01"
  cluster:
    server: "https://10.74.34.11:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TURZeE1EQTVNemN4TjFvWERUTXlNRFl3TnpBNU16Y3hOMW93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUt6TjVqSUM4Y2lqCnY0RWcwTDlLeElNU3NVNTNNb1N6LzJzYmVIMWVtVFpKOVBra2ptNWJZS\
      TlsQ0k5aDBxZWFYdys2dTgwUjd0aWYKMkFPS3hyTFZHU1N4cjRvUnU4RmlCUFZpV0dZQzUwV1ZHe\
      EpOSWdlalh4YUFpRjlCNkZCTm1PTk9lSEpYQ0xNQwp3Y1ZWOUdvQkd6VjVESk1sc09RSVZxT0taa\
      nAzVkZESW1oMmFtRGZPMjhCZ0VtaWhkaHZ5bW1FM3JtNGo4eUwyCkZlcFBiTjY1KzFidkk4anFOb\
      1daa0h3UkNFWXJzT3BtQmJOZ2pYOTBISDRLSVVPaUtjZm8xdEgxbTRTU3FDMmYKN3FsRzYxU1FGU\
      jJjc0QwT0hMUjVaVm1wNm9yUm95bUNmYXJtWlJnQnVhVTQzakJXQnZJd0JLVXNMN25pVDhxVQpmV\
      FhncXgyOU54VUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGUFdvbHBzSGNYSWVjRC9INkRuRTFWTm5NdFFBTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQmlyMUhzYWtFRkxyQitEYUZjQ1BnMTBQZVR2K2tMRDhaTE4xW\
      mhUUkxiZ0FyNFhTOHMrN1VmZkpuKwpCUnBXdFhCdWY1QWZGdHNwR2pPZFZuZkNNUFk3KzlUU3JNQ\
      mhRN3Q5dTlTSFcyU3JZSWJoWVNteVMwRitqNy82CjFPR0VOa2s3Q3Z3a1BML1V1WkFlZEpnVStVY\
      St5b1BJNFdHL0FoY0RoK1RnRlo2MGdLSjVXYjhIRmZkUkdOaFAKaElJOEZnVFFydGp6YUhHMXFBd\
      3c4STFWZGNkUXhMMTVZNUpxUjRXWUNRdkIwRjVhTHk0MllQV0MrZXFxUlNDcQp1SU5HdkNFckwwU\
      3NCSEI0T3EyU0pNT2hhdHRYUW1QU2UwckFrS25YdFlab1RuOWx1bDMwSjc1NWdrRmQ0eDR0CnhJT\
      mdpRmxHSDdnKzN3bERMbEFqSmZCWDJEUTQKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "open"
  user:
    token: "kubeconfig-user-fdt29smw2v:2svbssm5lk62h97mc9vnv9kq7k75cc4hz7tgdkx4hhwrr8lqtssz7m"


contexts:
- name: "open"
  context:
    user: "open"
    cluster: "open"
- name: "open-cluster01"
  context:
    user: "open"
    cluster: "open-cluster01"

current-context: "open"
