apiVersion: v1
kind: Pod
metadata:
  name: env.evoliatis.fr
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-demo
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
    env:
    - name: UTILISATEUR
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: login
