apiVersion: v1
kind: Service
metadata:
  name: slave-01-en-ligne-evoliatis-fr
  labels:
    app: nginx
spec:
  ports:
  - port: 31000
    nodePort: 31000
    targetPort: nginx-port
    protocol: TCP
  selector:
    app: nginx
  type: NodePort
