apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: 31002
    nodePort: 31002
    targetPort: deploy-port
    protocol: TCP
  selector:
    app: nginx
  type: NodePort
