apiVersion: v1
kind: Namespace
metadata:
  name: stress
  labels:
    app: stress
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  labels:
    app: stress
  namespace: stress
spec:
  hard:
    requests.memory: 32Mi
    requests.cpu: "100m"
    limits.memory: 64Mi
    limits.cpu: "200m"  