apiVersion: v1
kind: ReplicationController
metadata:
  name: webservice
  labels:
    app: webservice
spec:
  replicas: 3
  selector:
    app: webservice
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http-port
          containerPort: 80
