apiVersion: v1
kind: Service
metadata:
  name: webservice-service
  labels:
    app: webservice  
spec:
  ports:
  - port: 31000
    nodePort: 31000
    targetPort: http-port
    protocol: TCP
  selector:
    app: webservice
  type: NodePort
