apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stress-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: stress
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
