apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wordpress-rules
  namespace: app-wordpress
spec:
  rules:

  - host: wordpress.evoliatis.lan
    http:
      paths:
      - path: /
        backend:
          serviceName: wordpress-service
          servicePort: 31000

  - host: phpmyadmin.evoliatis.lan
    http:
      paths:
      - path: /
        backend:
          serviceName: phpmyadmin-service
          servicePort: 32000


