apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 31306
    nodePort: 31306
    targetPort: mysql-port
    protocol: TCP
  selector:
    app: mysql
  type: NodePort
