apiVersion: v1
kind: Namespace
metadata:
  name: app-nginx
  labels:
    app: app-nginx
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-front
  namespace: app-nginx
  labels:
    app: nginx
    tier: frontend
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - image: nginx:1.15
        name: nginx
        ports:
        - containerPort: 80
          name: nginx-port
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: app-nginx
  labels:
    app: nginx
    tier: frontend
spec:
  selector:
    app: nginx
  ports:
    - port: 31500
      targetPort: nginx-port
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-rules
  namespace: app-nginx
spec:
  rules:

  - host: test.evoliatis.lan
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-service
          servicePort: 31500
